install all packages in one apt-get sentence

diff --git a/eldap b/eldap
--- a/eldap
+++ b/eldap
@@ -213,14 +213,21 @@ TIMELIMIT       $TIMELIMIT
 EOF
 
 # setup base packages
-for package in "${BASE_PKGS[@]}"
-do
-install_package "$package"
-	if [ $? -ne 0 ]; then
-		error "Can't install package $package, please check your apt repository"
-		exit 1
-	fi
-done
+packages=$(echo $BASE_PKGS | awk -F "(" '{print $2}' | awk -F ")" '{print $1}')
+install_package $packages
+if [ $? -ne 0 ]; then
+	error "Can't install base packages, please check your apt repository"
+	exit 1
+fi
+
+# for package in "${BASE_PKGS[@]}"
+#do
+#install_package "$package"
+#	if [ $? -ne 0 ]; then
+#		error "Can't install package $package, please check your apt repository"
+#		exit 1
+#	fi
+#done
 
 # setup utilities
 for package in "${PACKAGES[@]}"
